# this file is being used to ignore vulnerabilities while fixes are unavailable.
# Docs at https://oss.anchore.com/docs/guides/vulnerability/filter-results/#ignore-specific-vulnerabilities-or-packages

ignore:
