services:
  postgres:
    image: docker.io/postgres:16
    environment:
      - POSTGRES_USER=opendlp
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
    volumes:
      - sqla_opendlp_pgdata:/var/lib/postgresql/data

volumes:
  sqla_opendlp_pgdata:
