services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - PYTHONUNBUFFERED=1
    # define DB_PASSWORD in the .env file
    env_file:
      - .env
      - .env.prod
    ports:
      - "8080:8080"
    entrypoint: /app/bin/gunicorn
    command:
      - --bind=0.0.0.0:8080
      - --log-level=info
      - "opendlp.entrypoints.flask_app:create_app()"

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=opendlp
    # define POSTGRES_PASSWORD in the .env file
    env_file:
      - .env
      - .env.prod
    volumes:
      - sqla_opendlp_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  sqla_opendlp_pgdata:
