services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    ports:
      - "5005:5005"
    entrypoint:
      - /app/bin/flask
      - run
      - --host=0.0.0.0
      - --port=5005
      - --debug
    env_file: .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: uv.lock

  app_celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - PYTHONUNBUFFERED=1
    # define DB_PASSWORD in the .env file
    env_file: .env
    entrypoint:
      - /app/bin/celery
      - --app=opendlp.entrypoints.celery.tasks
      - worker
      - --loglevel=info
    networks:
      - opendlp_prod_net
    restart: always

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=opendlp
      - POSTGRES_PASSWORD=abc123
    volumes:
      - sqla_opendlp_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  sqla_opendlp_pgdata:
