services:
  postgres_test:
    image: docker.io/postgres:16
    environment:
      - POSTGRES_USER=opendlp
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54322:5432"
    networks:
      - test_net
    # for test we don't use a volume so it is created fresh each time

  redis_test:
    image: redis:alpine
    ports:
      - "63792:6379"
    networks:
      - test_net

networks:
  test_net:
