services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - PYTHONUNBUFFERED=1
    # define DB_PASSWORD in the .env file
    env_file: .env
    ports:
      - "8080:8080"
    entrypoint:
      - /app/bin/gunicorn
      - --bind=0.0.0.0:8080
      - --log-level=info
      - app:app

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=opendlp
    # define POSTGRES_PASSWORD in the .env file
    env_file: .env
    volumes:
      - sqla_opendlp_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  sqla_opendlp_pgdata:
