services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    ports:
      - "5005:5005"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: uv.lock

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=opendlp
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
    volumes:
      - sqla_opendlp_pgdata:/var/lib/postgresql/data

volumes:
  sqla_opendlp_pgdata:
