import tempfile
from collections.abc import Callable
from pathlib import Path

from flask import Flask, current_app
from sortition_algorithms import adapters
from sqlalchemy.orm import sessionmaker

from opendlp import config
from opendlp.adapters import database
from opendlp.adapters.email import ConsoleEmailAdapter, EmailAdapter, SMTPEmailAdapter
from opendlp.adapters.sortition_algorithms import CSVGSheetDataSource
from opendlp.adapters.template_renderer import FlaskTemplateRenderer, TemplateRenderer
from opendlp.adapters.url_generator import FlaskURLGenerator, URLGenerator
from opendlp.config import SMTPEmailCfg, get_config, get_db_uri
from opendlp.service_layer import unit_of_work

_session_factory_cache: dict[str, sessionmaker] = {}


def bootstrap_session_factory(
    start_orm: bool = True,
    session_factory: sessionmaker | None = None,
) -> sessionmaker:
    if start_orm:
        database.start_mappers()

    if session_factory is None:
        db_uri = get_db_uri()
        cached = _session_factory_cache.get(db_uri)
        if cached is None:
            cached = database.create_session_factory(db_uri)
            _session_factory_cache[db_uri] = cached
        session_factory = cached

    return session_factory


def dispose_cached_engines() -> None:
    """Dispose all engines cached by ``bootstrap_session_factory`` and clear the cache.

    Call this from post-fork hooks (Celery ``worker_process_init``, gunicorn
    ``post_fork``). SQLAlchemy connection pools must not be shared across a
    fork: the child inherits the parent's open file descriptors, so parent
    and children would race on the same TCP sockets. After disposal each
    child rebuilds its own pool on first use.
    """
    for factory in _session_factory_cache.values():
        factory.kw["bind"].dispose()
    _session_factory_cache.clear()


def bootstrap(
    start_orm: bool = True,
    uow: unit_of_work.AbstractUnitOfWork | None = None,
    session_factory: sessionmaker | None = None,
) -> unit_of_work.AbstractUnitOfWork:
    session_factory = bootstrap_session_factory(start_orm, session_factory)

    if uow is None:
        uow = unit_of_work.SqlAlchemyUnitOfWork(session_factory)

    return uow


UowFactory = Callable[[], unit_of_work.AbstractUnitOfWork]


def default_uow_factory() -> unit_of_work.AbstractUnitOfWork:
    """Production UnitOfWork factory: a SqlAlchemyUnitOfWork over the cached session factory."""
    return unit_of_work.SqlAlchemyUnitOfWork(bootstrap_session_factory())


def get_flask_uow() -> unit_of_work.AbstractUnitOfWork:
    """Return a UnitOfWork for the current request, using the app-configured factory.

    Must be called within a Flask application context. The factory is registered
    on the app by ``create_app`` (``app.extensions["uow_factory"]``); tests can
    inject a fake factory there. CLI and Celery code run outside an app context
    and must keep using ``bootstrap()`` with an explicit ``session_factory``.
    """
    factory: UowFactory = current_app.extensions.get("uow_factory", default_uow_factory)
    return factory()


def get_flask_uow_factory() -> UowFactory:
    """Return the app-configured UnitOfWork factory itself.

    For callers that need to create multiple UnitOfWork instances or pass the
    factory down into a service. Must be called within a Flask application context.
    """
    factory: UowFactory = current_app.extensions.get("uow_factory", default_uow_factory)
    return factory


def update_data_source_from_assembly_gsheet(
    gsheet_data_source: adapters.GSheetDataSource,
) -> adapters.GSheetDataSource | CSVGSheetDataSource:
    """
    Override the datasource if environment variables indicate we are testing.

    In production: returns the DataSource object passed in.
    In tests (when USE_CSV_DATA_SOURCE=true): returns CSVFileDataSource instead.

    Args:
        gsheet_data_source: the GSheetDataSource object generated by the normal code.

    Returns:
        AbstractDataSource instance (either GSheetDataSource passed in or CSVFileDataSource)
    """
    if not config.use_csv_data_source_for_testing():
        return gsheet_data_source
    test_dir = config.get_csv_test_data_dir()
    # Create temp directory for output files (selected/remaining)
    temp_output_dir = Path(tempfile.gettempdir()) / "opendlp_selection_output"
    temp_output_dir.mkdir(exist_ok=True)

    csv_data_source = adapters.CSVFileDataSource(
        features_file=test_dir / "features.csv",
        people_file=test_dir / "candidates.csv",
        already_selected_file=test_dir / "already_selected.csv",
        selected_file=temp_output_dir / "selected.csv",
        remaining_file=temp_output_dir / "remaining.csv",
    )
    return CSVGSheetDataSource(csv_data_source=csv_data_source, gsheet_data_source=gsheet_data_source)


def get_email_adapter() -> EmailAdapter:
    """Get the configured email adapter based on application configuration.

    Returns:
        EmailAdapter instance (ConsoleEmailAdapter or SMTPEmailAdapter)

    Raises:
        ValueError: If email adapter type is unknown
    """
    app_config = get_config()
    adapter_type = app_config.EMAIL_ADAPTER.lower().strip()

    if adapter_type == "console":
        return ConsoleEmailAdapter()

    if adapter_type == "smtp":
        smtp_config = SMTPEmailCfg.from_env()
        return SMTPEmailAdapter(
            host=smtp_config.host,
            port=smtp_config.port,
            username=smtp_config.username,
            password=smtp_config.password,
            use_tls=smtp_config.use_tls,
            default_from_email=smtp_config.from_email,
            default_from_name=smtp_config.from_name,
        )

    raise ValueError(f"Unknown email adapter type: '{adapter_type}'. Valid options are: 'console', 'smtp'")


def get_template_renderer(app: Flask) -> TemplateRenderer:
    """Get the template renderer for the Flask application.

    Args:
        app: Flask application instance

    Returns:
        TemplateRenderer instance (FlaskTemplateRenderer)
    """
    return FlaskTemplateRenderer(app)


def get_url_generator(app: Flask) -> URLGenerator:
    """Get the URL generator for the Flask application.

    Args:
        app: Flask application instance

    Returns:
        URLGenerator instance (FlaskURLGenerator)
    """
    return FlaskURLGenerator(app)
