"""allow multiple registration pages per assembly

Revision ID: 0be930d1ad89
Revises: 3d7f07de5b72
Create Date: 2026-08-06 11:52:30.092156

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0be930d1ad89"
down_revision: str | Sequence[str] | None = "3d7f07de5b72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("registration_pages", sa.Column("name", sa.String(length=100), server_default="", nullable=False))
    op.add_column("registration_pages", sa.Column("language", sa.String(length=20), server_default="", nullable=False))
    op.drop_constraint(op.f("registration_pages_assembly_id_key"), "registration_pages", type_="unique")
    op.create_index(op.f("ix_registration_pages_assembly_id"), "registration_pages", ["assembly_id"], unique=False)
    op.create_index(
        "ix_registration_pages_assembly_name_unique",
        "registration_pages",
        ["assembly_id", "name"],
        unique=True,
        postgresql_where=sa.text("name != ''"),
    )
    # ### end Alembic commands ###
    # Existing pages predate naming. Each assembly had at most one page, so a
    # single literal cannot collide under the partial unique index above.
    op.execute("UPDATE registration_pages SET name = 'Registration page' WHERE name = ''")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_registration_pages_assembly_name_unique",
        table_name="registration_pages",
        postgresql_where=sa.text("name != ''"),
    )
    op.drop_index(op.f("ix_registration_pages_assembly_id"), table_name="registration_pages")
    op.create_unique_constraint(
        op.f("registration_pages_assembly_id_key"),
        "registration_pages",
        ["assembly_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("registration_pages", "language")
    op.drop_column("registration_pages", "name")
    # ### end Alembic commands ###
