"""add progress column to selection_run_records

Revision ID: 0dd36337f48e
Revises: 3027292d7d21
Create Date: 2026-04-09 16:43:31.024482

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0dd36337f48e"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "3027292d7d21"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("selection_run_records", sa.Column("progress", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("selection_run_records", "progress")
    # ### end Alembic commands ###
