"""Update enum columns to use custom type

Revision ID: 1aea6aa317b3
Revises: 2a4a39b93c61
Create Date: 2025-08-12 15:07:09.660991

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1aea6aa317b3"
down_revision: str | Sequence[str] | None = "2a4a39b93c61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
