"""add derivation type and config plus mapping entries table

Revision ID: 1d96def856f6
Revises: aedb402e99ad
Create Date: 2026-09-08 15:59:31.294923

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d96def856f6"
down_revision: str | Sequence[str] | None = "aedb402e99ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "respondent_field_mapping_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("lookup_key", sa.String(length=255), nullable=False),
        sa.Column("output_value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["respondent_field_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_respondent_field_mapping_entries_field_key",
        "respondent_field_mapping_entries",
        ["field_id", "lookup_key"],
        unique=True,
    )
    # EnumAsString stores plain strings; autogenerate cannot name the custom type.
    op.add_column("respondent_field_definitions", sa.Column("derivation_type", sa.String(length=32), nullable=True))
    op.add_column(
        "respondent_field_definitions",
        sa.Column("derivation_config", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("respondent_field_definitions", "derivation_kind")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "respondent_field_definitions",
        sa.Column("derivation_kind", sa.VARCHAR(length=100), autoincrement=False, nullable=False, server_default=""),
    )
    op.drop_column("respondent_field_definitions", "derivation_config")
    op.drop_column("respondent_field_definitions", "derivation_type")
    op.drop_index("ix_respondent_field_mapping_entries_field_key", table_name="respondent_field_mapping_entries")
    op.drop_table("respondent_field_mapping_entries")
    # ### end Alembic commands ###
