"""add auto export to assembly export gsheets

Revision ID: 1eacb37ea6a2
Revises: ef642787cb4a
Create Date: 2026-09-30 11:11:05.806968

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1eacb37ea6a2"
down_revision: str | Sequence[str] | None = "ef642787cb4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assembly_export_gsheets",
        sa.Column("auto_export", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "assembly_export_gsheets",
        sa.Column("auto_export_status_filter", sa.String(length=50), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assembly_export_gsheets", "auto_export_status_filter")
    op.drop_column("assembly_export_gsheets", "auto_export")
    # ### end Alembic commands ###
