"""add_already_selected_tab_to_assembly_gsheets

Revision ID: 23993534552f
Revises: 92511de414a4
Create Date: 2025-12-10 15:24:56.269791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23993534552f"  # pragma: allowlist secret
down_revision: str | Sequence | None = "92511de414a4"  # pragma: allowlist secret
branch_labels: str | Sequence | None = None
depends_on: str | Sequence | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assembly_gsheets",
        sa.Column("already_selected_tab", sa.String(length=100), nullable=False, server_default="Selected"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assembly_gsheets", "already_selected_tab")
    # ### end Alembic commands ###
