"""Update assemblies.first_assembly_date column to be nullable

Revision ID: 357851019236
Revises: 36f822f76b45
Create Date: 2025-08-15 13:09:10.940013

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "357851019236"
down_revision: str | Sequence[str] | None = "36f822f76b45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assemblies", "first_assembly_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assemblies", "first_assembly_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
