"""add help_text to respondent_field_definitions

Revision ID: 35e8f845a79f
Revises: 1d96def856f6
Create Date: 2026-09-09 10:47:51.479161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35e8f845a79f"
down_revision: str | Sequence[str] | None = "1d96def856f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("respondent_field_definitions", sa.Column("help_text", sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("respondent_field_definitions", "help_text")
    # ### end Alembic commands ###
