"""add selection run record table

Revision ID: 38ce30978f41
Revises: 9a412ec321c2
Create Date: 2025-09-24 17:03:47.239890

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import opendlp.adapters.orm

# revision identifiers, used by Alembic.
revision: str = "38ce30978f41"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "9a412ec321c2"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "selection_run_records",
        sa.Column("task_id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("assembly_id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("celery_task_id", sa.String(length=50), nullable=False),
        sa.Column("log_messages", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("settings_used", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("completed_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assembly_id"], ["assemblies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_selection_run_records_assembly_id"), "selection_run_records", ["assembly_id"], unique=False
    )
    op.create_index(
        op.f("ix_selection_run_records_celery_task_id"), "selection_run_records", ["celery_task_id"], unique=False
    )
    op.create_index(op.f("ix_selection_run_records_created_at"), "selection_run_records", ["created_at"], unique=False)
    op.create_index(op.f("ix_selection_run_records_status"), "selection_run_records", ["status"], unique=False)
    op.create_index(op.f("ix_selection_run_records_task_type"), "selection_run_records", ["task_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_selection_run_records_task_type"), table_name="selection_run_records")
    op.drop_index(op.f("ix_selection_run_records_status"), table_name="selection_run_records")
    op.drop_index(op.f("ix_selection_run_records_created_at"), table_name="selection_run_records")
    op.drop_index(op.f("ix_selection_run_records_celery_task_id"), table_name="selection_run_records")
    op.drop_index(op.f("ix_selection_run_records_assembly_id"), table_name="selection_run_records")
    op.drop_table("selection_run_records")
    # ### end Alembic commands ###
