"""attribute respondents to their registration page

Revision ID: 4b420dba5d65
Revises: e2312430cf2f
Create Date: 2026-08-06 12:46:44.030658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b420dba5d65"
down_revision: str | Sequence[str] | None = "e2312430cf2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("respondents", sa.Column("registration_page_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_respondents_registration_page_id"), "respondents", ["registration_page_id"], unique=False)
    op.create_foreign_key(
        "respondents_registration_page_id_fkey",
        "respondents",
        "registration_pages",
        ["registration_page_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("respondents_registration_page_id_fkey", "respondents", type_="foreignkey")
    op.drop_index(op.f("ix_respondents_registration_page_id"), table_name="respondents")
    op.drop_column("respondents", "registration_page_id")
    # ### end Alembic commands ###
