"""add registration documents

Revision ID: 62e37f3ab7e8
Revises: 57d73add6894
Create Date: 2026-07-17 13:03:31.424646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import opendlp.adapters.orm

# revision identifiers, used by Alembic.
revision: str = "62e37f3ab7e8"
down_revision: str | Sequence[str] | None = "57d73add6894"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_page_id", sa.UUID(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("label", sa.String(), server_default="", nullable=False),
        sa.Column("original_filename", sa.String(length=255), server_default="", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["registration_page_id"], ["registration_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_registration_documents_page_sha_unique",
        "registration_documents",
        ["registration_page_id", "sha256"],
        unique=True,
    )
    op.create_index(
        op.f("ix_registration_documents_registration_page_id"),
        "registration_documents",
        ["registration_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_registration_documents_registration_page_id"), table_name="registration_documents")
    op.drop_index("ix_registration_documents_page_sha_unique", table_name="registration_documents")
    op.drop_table("registration_documents")
    # ### end Alembic commands ###
