"""extend selection run record with user, comment, status, selected_ids and run_report

Revision ID: 65bda39a
Revises: e2da2a1682d2
Create Date: 2025-11-19 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import opendlp.adapters.orm

# revision identifiers, used by Alembic.
revision: str = "65bda39a"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "e2da2a1682d2"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "selection_run_records",
        sa.Column(
            "user_id",
            opendlp.adapters.orm.CrossDatabaseUUID(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_selection_run_records_user_id"), "selection_run_records", ["user_id"], unique=False)
    op.add_column("selection_run_records", sa.Column("comment", sa.Text(), nullable=False, server_default=""))
    op.add_column("selection_run_records", sa.Column("status_stages", sa.JSON(), nullable=True))
    op.add_column("selection_run_records", sa.Column("selected_ids", sa.JSON(), nullable=True))
    op.add_column("selection_run_records", sa.Column("run_report", opendlp.adapters.orm.RunReportJSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("selection_run_records", "run_report")
    op.drop_column("selection_run_records", "selected_ids")
    op.drop_column("selection_run_records", "status_stages")
    op.drop_column("selection_run_records", "comment")
    op.drop_index(op.f("ix_selection_run_records_user_id"), table_name="selection_run_records")
    op.drop_column("selection_run_records", "user_id")
    # ### end Alembic commands ###
