"""add registration pages

Revision ID: 6c832644862b
Revises: dc970a98750c
Create Date: 2026-05-14 21:25:16.672615

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from opendlp.adapters import orm
from opendlp.domain.registration_page import RegistrationPageSource

# revision identifiers, used by Alembic.
revision: str = "6c832644862b"
down_revision: str | Sequence[str] | None = "dc970a98750c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_pages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assembly_id", sa.UUID(), nullable=False),
        sa.Column("url_slug", sa.String(length=100), nullable=False),
        sa.Column("short_url_slug", sa.String(length=30), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("preview_token", sa.String(length=64), nullable=False),
        sa.Column("source_type", orm.EnumAsString(RegistrationPageSource, 32), nullable=False),
        sa.Column("thank_you_html", sa.Text(), nullable=False),
        sa.Column("created_at", orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("updated_at", orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assembly_id"], ["assemblies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assembly_id"),
    )
    op.create_index(op.f("ix_registration_pages_is_published"), "registration_pages", ["is_published"], unique=False)
    op.create_index(
        "ix_registration_pages_short_url_slug_unique",
        "registration_pages",
        ["short_url_slug"],
        unique=True,
        postgresql_where=sa.text("short_url_slug != ''"),
    )
    op.create_index(
        "ix_registration_pages_url_slug_unique",
        "registration_pages",
        ["url_slug"],
        unique=True,
        postgresql_where=sa.text("url_slug != ''"),
    )
    op.create_table(
        "registration_page_html_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_page_id", sa.UUID(), nullable=False),
        sa.Column("form_html", sa.Text(), nullable=False),
        sa.Column("created_at", orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("updated_at", orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["registration_page_id"], ["registration_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registration_page_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registration_page_html_sources")
    op.drop_index(
        "ix_registration_pages_url_slug_unique",
        table_name="registration_pages",
        postgresql_where=sa.text("url_slug != ''"),
    )
    op.drop_index(
        "ix_registration_pages_short_url_slug_unique",
        table_name="registration_pages",
        postgresql_where=sa.text("short_url_slug != ''"),
    )
    op.drop_index(op.f("ix_registration_pages_is_published"), table_name="registration_pages")
    op.drop_table("registration_pages")
    # ### end Alembic commands ###
