"""make number_to_select non-nullable with default value

Revision ID: 92511de414a4
Revises: 65bda39a
Create Date: 2025-11-20 13:41:20.925048

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92511de414a4"
down_revision: str | Sequence[str] | None = "65bda39a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, update any existing NULL values to 0
    op.execute("UPDATE assemblies SET number_to_select = 0 WHERE number_to_select IS NULL")

    # Then make the column NOT NULL
    op.alter_column(
        "assemblies", "number_to_select", existing_type=sa.INTEGER(), nullable=False, server_default=sa.text("0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assemblies", "number_to_select", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
