"""add assembly_respondent_gsheets table

Revision ID: 97bd06e3418a
Revises: 5e06447b7861
Create Date: 2026-07-08 11:08:18.192742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import opendlp.adapters.orm

# revision identifiers, used by Alembic.
revision: str = "97bd06e3418a"
down_revision: str | Sequence[str] | None = "5e06447b7861"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assembly_respondent_gsheets",
        sa.Column("assembly_respondent_gsheet_id", sa.UUID(), nullable=False),
        sa.Column("assembly_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("worksheet_name", sa.String(length=100), nullable=False),
        sa.Column("id_column", sa.String(length=100), nullable=False),
        sa.Column("created_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("updated_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assembly_id"], ["assemblies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("assembly_respondent_gsheet_id"),
    )
    op.create_index(
        op.f("ix_assembly_respondent_gsheets_assembly_id"), "assembly_respondent_gsheets", ["assembly_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assembly_respondent_gsheets_assembly_id"), table_name="assembly_respondent_gsheets")
    op.drop_table("assembly_respondent_gsheets")
    # ### end Alembic commands ###
