"""remove gsheet_url from assembly

Revision ID: 9a412ec321c2
Revises: 1d7768eabf9a
Create Date: 2025-09-17 16:47:31.478897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a412ec321c2"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "1d7768eabf9a"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assemblies", "gsheet_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assemblies", sa.Column("gsheet_url", sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
