"""add registration images

Revision ID: a644849bb5d2
Revises: 28ad0135cfe8
Create Date: 2026-06-11 17:21:52.662358

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from opendlp.adapters import orm

# revision identifiers, used by Alembic.
revision: str = "a644849bb5d2"
down_revision: str | Sequence[str] | None = "28ad0135cfe8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_page_id", sa.UUID(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("alt", sa.String(), nullable=False, server_default=""),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["registration_page_id"], ["registration_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_registration_images_page_sha_unique", "registration_images", ["registration_page_id", "sha256"], unique=True
    )
    op.create_index(
        op.f("ix_registration_images_registration_page_id"),
        "registration_images",
        ["registration_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_registration_images_registration_page_id"), table_name="registration_images")
    op.drop_index("ix_registration_images_page_sha_unique", table_name="registration_images")
    op.drop_table("registration_images")
    # ### end Alembic commands ###
