"""add settings_confirmed to assembly_csv

Revision ID: ae1e11ac18e2
Revises: fff891c47e1e
Create Date: 2026-03-09 15:29:08.256324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae1e11ac18e2"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "fff891c47e1e"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assembly_csv", sa.Column("settings_confirmed", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assembly_csv", "settings_confirmed")
    # ### end Alembic commands ###
