"""add columns and tables for totp 2fa

Revision ID: d0da5f725d79
Revises: 31c94e088009
Create Date: 2026-01-20 16:58:29.964805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import opendlp.adapters.orm

# revision identifiers, used by Alembic.
revision: str = "d0da5f725d79"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "31c94e088009"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "totp_verification_attempts",
        sa.Column("id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("user_id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("attempted_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_totp_verification_attempts_attempted_at"), "totp_verification_attempts", ["attempted_at"], unique=False
    )
    op.create_index(
        op.f("ix_totp_verification_attempts_user_id"), "totp_verification_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "two_factor_audit_log",
        sa.Column("id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("user_id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("performed_by", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=True),
        sa.Column("timestamp", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["performed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_two_factor_audit_log_timestamp"), "two_factor_audit_log", ["timestamp"], unique=False)
    op.create_index(op.f("ix_two_factor_audit_log_user_id"), "two_factor_audit_log", ["user_id"], unique=False)
    op.create_table(
        "user_backup_codes",
        sa.Column("id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("user_id", opendlp.adapters.orm.CrossDatabaseUUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("used_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=True),
        sa.Column("created_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_backup_codes_user_id", "user_backup_codes", ["user_id"], unique=False)
    op.add_column("users", sa.Column("totp_secret_encrypted", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("totp_enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("totp_enabled_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_enabled_at")
    op.drop_column("users", "totp_enabled")
    op.drop_column("users", "totp_secret_encrypted")
    op.drop_index("ix_user_backup_codes_user_id", table_name="user_backup_codes")
    op.drop_table("user_backup_codes")
    op.drop_index(op.f("ix_two_factor_audit_log_user_id"), table_name="two_factor_audit_log")
    op.drop_index(op.f("ix_two_factor_audit_log_timestamp"), table_name="two_factor_audit_log")
    op.drop_table("two_factor_audit_log")
    op.drop_index(op.f("ix_totp_verification_attempts_user_id"), table_name="totp_verification_attempts")
    op.drop_index(op.f("ix_totp_verification_attempts_attempted_at"), table_name="totp_verification_attempts")
    op.drop_table("totp_verification_attempts")
    # ### end Alembic commands ###
