"""add user data agreement agreed at timestamp

Revision ID: d87ee6f88367
Revises: 3b1a6d409159
Create Date: 2025-08-29 12:23:23.624611

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import opendlp.adapters.orm

# revision identifiers, used by Alembic.
revision: str = "d87ee6f88367"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "3b1a6d409159"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("user_data_agreement_agreed_at", opendlp.adapters.orm.TZAwareDatetime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_data_agreement_agreed_at")
    # ### end Alembic commands ###
