"""add target_categories and respondents tables

Revision ID: dbb4dc5c616b
Revises: f1g2h3i4j5k6
Create Date: 2026-02-13 09:37:34.730204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from opendlp.adapters.orm import CrossDatabaseUUID, EnumAsString, TargetValueListJSON, TZAwareDatetime
from opendlp.domain.value_objects import RespondentSourceType, RespondentStatus

# revision identifiers, used by Alembic.
revision: str = "dbb4dc5c616b"
down_revision: str | Sequence[str] | None = "f1g2h3i4j5k6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_categories",
        sa.Column("id", CrossDatabaseUUID(), nullable=False),
        sa.Column("assembly_id", CrossDatabaseUUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("values", TargetValueListJSON, nullable=False),
        sa.Column("created_at", TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("updated_at", TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assembly_id"], ["assemblies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_target_categories_assembly_id"), "target_categories", ["assembly_id"], unique=False)
    op.create_index("ix_target_categories_assembly_name", "target_categories", ["assembly_id", "name"], unique=True)
    op.create_index(
        "ix_target_categories_assembly_sort", "target_categories", ["assembly_id", "sort_order"], unique=False
    )
    op.create_table(
        "respondents",
        sa.Column("id", CrossDatabaseUUID(), nullable=False),
        sa.Column("assembly_id", CrossDatabaseUUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("selection_status", EnumAsString(RespondentStatus, 50), nullable=False),
        sa.Column("selection_run_id", CrossDatabaseUUID(), nullable=True),
        sa.Column("consent", sa.Boolean(), nullable=True),
        sa.Column("stay_on_db", sa.Boolean(), nullable=True),
        sa.Column("eligible", sa.Boolean(), nullable=True),
        sa.Column("can_attend", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("source_type", EnumAsString(RespondentSourceType, 50), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=False),
        sa.Column("attributes", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", TZAwareDatetime(timezone=True), nullable=False),
        sa.Column("updated_at", TZAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assembly_id"], ["assemblies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["selection_run_id"], ["selection_run_records.task_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_respondents_assembly_external", "respondents", ["assembly_id", "external_id"], unique=True)
    op.create_index(op.f("ix_respondents_assembly_id"), "respondents", ["assembly_id"], unique=False)
    op.create_index(op.f("ix_respondents_email"), "respondents", ["email"], unique=False)
    op.create_index(
        "ix_respondents_selection",
        "respondents",
        ["assembly_id", "selection_status", "eligible", "can_attend"],
        unique=False,
    )
    op.create_index(op.f("ix_respondents_selection_run_id"), "respondents", ["selection_run_id"], unique=False)
    op.create_index(op.f("ix_respondents_selection_status"), "respondents", ["selection_status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_respondents_selection_status"), table_name="respondents")
    op.drop_index(op.f("ix_respondents_selection_run_id"), table_name="respondents")
    op.drop_index("ix_respondents_selection", table_name="respondents")
    op.drop_index(op.f("ix_respondents_email"), table_name="respondents")
    op.drop_index(op.f("ix_respondents_assembly_id"), table_name="respondents")
    op.drop_index("ix_respondents_assembly_external", table_name="respondents")
    op.drop_table("respondents")
    op.drop_index("ix_target_categories_assembly_sort", table_name="target_categories")
    op.drop_index("ix_target_categories_assembly_name", table_name="target_categories")
    op.drop_index(op.f("ix_target_categories_assembly_id"), table_name="target_categories")
    op.drop_table("target_categories")
    # ### end Alembic commands ###
