"""drop source_reference from respondents

Revision ID: dc970a98750c
Revises: bc31250a8ad0
Create Date: 2026-05-12 11:30:48.315644

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc970a98750c"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "bc31250a8ad0"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("respondents", "source_reference")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "respondents",
        sa.Column(
            "source_reference",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###
