"""add number_to_select field to assemblies

Revision ID: e2da2a1682d2
Revises: 38ce30978f41
Create Date: 2025-09-30 14:47:08.408603

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2da2a1682d2"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "38ce30978f41"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assemblies", sa.Column("number_to_select", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assemblies", "number_to_select")
    # ### end Alembic commands ###
