"""add_remaining_ids_to_selection_run_records

Revision ID: fff891c47e1e
Revises: 9b7ce3e7684e
Create Date: 2026-02-25 17:05:03.612478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fff891c47e1e"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "9b7ce3e7684e"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "selection_run_records", sa.Column("remaining_ids", postgresql.JSON(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("selection_run_records", "remaining_ids")
    # ### end Alembic commands ###
