"""ABOUTME: Flask context processors for adding variables to template context
ABOUTME: Provides functions that inject common variables into all templates"""

import contextlib
import hashlib
import json
import subprocess
from functools import cache
from pathlib import Path

from opendlp import config


def _get_file_hash(filepath: Path) -> str:
    """
    Generate a short hash of the file for cache-busting.

    Uses SHA256 hash of file contents, truncated to 8 characters.

    Returns:
        8-character hash string, or empty string if file doesn't exist
    """
    if not filepath.exists():
        return ""

    content = filepath.read_bytes()
    hash_value = hashlib.sha256(content).hexdigest()
    return hash_value[:8]


@cache
def get_css_hash() -> str:
    """
    Generate a short hash of the application.css file for cache-busting.

    Results are cached using functools.cache to avoid re-reading the file on every request.

    Returns:
        8-character hash string, or empty string if file doesn't exist
    """
    css_path = config.get_static_path() / "css" / "application.css"
    return _get_file_hash(css_path)


@cache
def get_util_js_hash() -> str:
    """
    Generate a short hash of the utilities.js file for cache-busting.

    Results are cached using functools.cache to avoid re-reading the file on every request.

    Returns:
        8-character hash string, or empty string if file doesn't exist
    """
    util_js_path = config.get_static_path() / "js" / "utilities.js"
    return _get_file_hash(util_js_path)


@cache
def get_alpine_js_hash() -> str:
    """
    Generate a short hash of the alpine-components.js file for cache-busting.

    Results are cached using functools.cache to avoid re-reading the file on every request.

    Returns:
        8-character hash string, or empty string if file doesn't exist
    """
    util_js_path = config.get_static_path() / "js" / "alpine-components.js"
    return _get_file_hash(util_js_path)


@cache
def get_opendlp_version() -> str:
    """
    Find the version of the OpenDLP app. It should be generated by running:

    git show --no-patch --format='%cd %h' --date=format:'%Y-%m-%d' HEAD

    which will show the date and short hash of the last commit. For deployment, this will have
    been written to the file `generated_version.txt` - so first check for that.

    If not, or if that file only contains "HEAD" then check if the parent directory contains ".git"
    then try running the git command.

    Otherwise return UNKNOWN
    """
    version_path = config.get_opendlp_version_path()
    if version_path.is_file():
        version = version_path.read_text(encoding="utf-8").strip()
        if version not in ("", "HEAD"):
            return version

    git_dir = config.get_git_dir_path()
    if git_dir.is_dir():
        result = subprocess.run(  # noqa: S603
            ["git", "show", "--no-patch", "--format=%cd %h", "--date=format:%Y-%m-%d", "HEAD"],
            cwd=git_dir.parent,
            capture_output=True,
            timeout=2,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()

    return "UNKNOWN"


@cache
def get_service_account_email() -> str:
    """
    Find the email address for the service account used for google spreadsheet access
    """
    auth_json_file = config.get_google_auth_json_path()
    if not auth_json_file.is_file():
        return "UNKNOWN"
    # we need this to not fail, so we just swallow all exceptions
    with contextlib.suppress(Exception), open(auth_json_file) as file:
        credentials = json.load(file)
        client_email = credentials["client_email"]
        assert isinstance(client_email, str)
        return client_email
    return "UNKNOWN"


def service_account_email_problem() -> str:
    """
    Find the email address for the service account used for google spreadsheet access
    """
    auth_json_file = config.get_google_auth_json_path()
    if auth_json_file == "/no-such-file":
        return "Could not find value of GOOGLE_AUTH_JSON_PATH"
    if not auth_json_file.is_file():
        return f"Auth JSON path {auth_json_file} is not a file."
    try:
        contents = auth_json_file.read_bytes()
    except Exception as error:
        return f"Could not read from {auth_json_file}: {error}"
    try:
        credentials = json.loads(contents)
    except json.JSONDecodeError as error:
        return f"Could not parse JSON from {auth_json_file}: {error}"
    try:
        client_email = credentials["client_email"]
    except Exception:
        return f"Could not find 'client_email' in credentials: {credentials}"
    if not isinstance(client_email, str):
        return f"client_email is not a string, it is: {client_email}"
    return f"No problem, found client email: {client_email}"


@cache
def get_site_banner_config() -> tuple[str, str]:
    """
    Get site banner configuration from environment.

    Returns:
        Tuple of (banner_text, banner_colour)
    """
    flask_config = config.get_config()
    return flask_config.SITE_BANNER_TEXT, flask_config.SITE_BANNER_COLOUR


def static_versioning_context_processor() -> dict[str, str]:
    """
    Flask context processor that adds static file version hashes to template context.

    Returns:
        Dictionary with css_hash and js_hash keys for use in templates
    """
    site_banner_text, site_banner_colour = get_site_banner_config()
    return {
        "css_hash": get_css_hash(),
        "util_js_hash": get_util_js_hash(),
        "alpine_js_hash": get_util_js_hash(),
        "opendlp_version": get_opendlp_version(),
        "google_service_account_email": get_service_account_email(),
        "site_banner_text": site_banner_text,
        "site_banner_colour": site_banner_colour,
    }
