"""ABOUTME: Flask context processors for adding variables to template context
ABOUTME: Provides functions that inject common variables into all templates"""

import hashlib
import subprocess
from functools import cache

from opendlp import config


@cache
def get_css_hash() -> str:
    """
    Generate a short hash of the application.css file for cache-busting.

    Uses SHA256 hash of file contents, truncated to 8 characters.
    Results are cached using functools.cache to avoid re-reading the file on every request.

    Returns:
        8-character hash string, or empty string if file doesn't exist
    """
    css_path = config.get_static_path() / "css" / "application.css"

    if not css_path.exists():
        return ""

    content = css_path.read_bytes()
    hash_value = hashlib.sha256(content).hexdigest()
    return hash_value[:8]


@cache
def get_opendlp_version() -> str:
    """
    Find the version of the OpenDLP app. It should be generated by running:

    git show --no-patch --format='%cd %h' --date=format:'%Y-%m-%d' HEAD

    which will show the date and short hash of the last commit. For deployment, this will have
    been written to the file `generated_version.txt` - so first check for that.

    If not, or if that file only contains "HEAD" then check if the parent directory contains ".git"
    then try running the git command.

    Otherwise return UNKNOWN
    """
    version_path = config.get_opendlp_version_path()
    if version_path.is_file():
        version = version_path.read_text(encoding="utf-8").strip()
        if version not in ("", "HEAD"):
            return version

    git_dir = config.get_git_dir_path()
    if git_dir.is_dir():
        result = subprocess.run(  # noqa: S603
            ["git", "show", "--no-patch", "--format=%cd %h", "--date=format:%Y-%m-%d", "HEAD"],
            cwd=git_dir.parent,
            capture_output=True,
            timeout=2,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout

    return "UNKNOWN"


def static_versioning_context_processor() -> dict[str, str]:
    """
    Flask context processor that adds static file version hashes to template context.

    Returns:
        Dictionary with css_hash key for use in templates
    """
    return {
        "css_hash": get_css_hash(),
        "opendlp_version": get_opendlp_version(),
    }
